services:
  fastapi:
    build:
      context: .
      dockerfile: api/Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    depends_on:
      - airflow
    restart: always

  airflow:
    build:
      context: .
      dockerfile: airflow/Dockerfile
    environment:
      - AIRFLOW__CORE__EXECUTOR=SequentialExecutor
      - AIRFLOW__CORE__LOAD_EXAMPLES=False
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=sqlite:////opt/airflow/airflow.db
    volumes:
      - ./airflow/dags:/opt/airflow/dags
      - ./models:/opt/airflow/models
      - ./data:/opt/airflow/data
      - ./scripts:/opt/airflow/scripts
    ports:
      - "8080:8080"
    restart: always
    command: bash -c "airflow db init && airflow users create --username airflow --firstname Airflow --lastname Admin --role Admin --email airflow@example.com --password airflow && airflow webserver & airflow scheduler"
